import { MetadataRoute } from 'next';

export default function robots(): MetadataRoute.Robots {
  const baseUrl = process.env.NEXT_PUBLIC_SITE_URL || 'https://dixis.io';
  
  return {
    rules: [
      {
        userAgent: '*',
        allow: [
          '/',
          '/products',
          '/products/*',
          '/producers',
          '/producers/*',
          '/about',
          '/contact',
          '/b2b',
          '/b2b/login',
          '/b2b/register',
          '/subscription',
          '/subscription/*',
          '/adoptions',
          '/become-producer',
          '/search',
          '/login',
          '/register',
          '/cart',
        ],
        disallow: [
          '/api/',
          '/admin/',
          '/dashboard/',
          '/checkout/',
          '/orders/',
          '/profile/',
          '/_next/',
          '/private/',
          '/temp/',
          '/tmp/',
          '/*.json$',
          '/*.xml$',
          '/404',
          '/500',
        ],
      },
      {
        userAgent: 'Googlebot',
        allow: [
          '/',
          '/products',
          '/products/*',
          '/producers',
          '/producers/*',
          '/about',
          '/contact',
          '/b2b',
          '/b2b/login',
          '/b2b/register',
          '/subscription',
          '/subscription/*',
          '/adoptions',
          '/become-producer',
          '/search',
          '/login',
          '/register',
          '/cart',
        ],
        disallow: [
          '/api/',
          '/admin/',
          '/dashboard/',
          '/checkout/',
          '/orders/',
          '/profile/',
          '/_next/',
          '/private/',
          '/temp/',
          '/tmp/',
          '/*.json$',
          '/*.xml$',
          '/404',
          '/500',
        ],
        crawlDelay: 1,
      },
      {
        userAgent: 'Bingbot',
        allow: [
          '/',
          '/products',
          '/products/*',
          '/producers',
          '/producers/*',
          '/about',
          '/contact',
          '/b2b',
          '/subscription',
          '/adoptions',
          '/search',
        ],
        disallow: [
          '/api/',
          '/admin/',
          '/dashboard/',
          '/checkout/',
          '/orders/',
          '/profile/',
          '/_next/',
          '/private/',
        ],
        crawlDelay: 2,
      },
      // Block aggressive crawlers from sensitive areas
      {
        userAgent: [
          'AhrefsBot',
          'SemrushBot',
          'MJ12bot',
          'DotBot',
        ],
        disallow: [
          '/api/',
          '/admin/',
          '/dashboard/',
          '/checkout/',
          '/orders/',
          '/profile/',
          '/cart/',
          '/b2b/dashboard/',
        ],
        crawlDelay: 10,
      },
    ],
    sitemap: `${baseUrl}/sitemap.xml`,
    host: baseUrl,
  };
}
