version: '3.8'

services:
  # MySQL Database
  mysql:
    image: mysql:8.0
    container_name: dixis_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-secretpassword}
      MYSQL_DATABASE: ${DB_DATABASE:-dixis_marketplace}
      MYSQL_USER: ${DB_USERNAME:-dixis}
      MYSQL_PASSWORD: ${DB_PASSWORD:-secretpassword}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - dixis-network

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: dixis_redis
    restart: unless-stopped
    command: redis-server --requirepass ${REDIS_PASSWORD:-redispassword}
    ports:
      - "6379:6379"
    networks:
      - dixis-network

  # PHP Application
  app:
    build:
      context: .
      dockerfile: Dockerfile.simple
    container_name: dixis_app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
      - ./storage:/var/www/html/storage
      - ./public:/var/www/html/public
    depends_on:
      - mysql
      - redis
    networks:
      - dixis-network
    ports:
      - "9000:9000"

  # Nginx Web Server
  nginx:
    image: nginx:alpine
    container_name: dixis_nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - dixis-network

volumes:
  mysql_data:
    driver: local

networks:
  dixis-network:
    driver: bridge