import { Category } from './types';

export const mockCategories: Category[] = [
  {
    id: 1,
    name: "Ελαιόλαδο & Λάδια",
    slug: "olive-oil-oils",
    description: "Εξαιρετικό παρθένο ελαιόλαδο και άλλα φυτικά λάδια από όλη την Ελλάδα",
    icon: "🫒",
    image: "/categories/olive-oil.jpg",
    parent_id: undefined,
    product_count: 45,
    is_featured: true,
    sort_order: 1,
    created_at: "2023-01-01T00:00:00Z",
    updated_at: "2024-01-01T00:00:00Z"
  },
  {
    id: 2,
    name: "Τυριά & Γαλακτοκομικά",
    slug: "cheese-dairy",
    description: "Παραδοσιακά ελληνικά τυριά και γαλακτοκομικά προϊόντα",
    icon: "🧀",
    image: "/categories/cheese.jpg",
    parent_id: undefined,
    product_count: 38,
    is_featured: true,
    sort_order: 2,
    created_at: "2023-01-01T00:00:00Z",
    updated_at: "2024-01-01T00:00:00Z"
  },
  {
    id: 3,
    name: "Μέλι & Μελισσοκομικά",
    slug: "honey-bee-products",
    description: "Φυσικό μέλι και προϊόντα μέλισσας από ελληνικούς μελισσοκόμους",
    icon: "🍯",
    image: "/categories/honey.jpg",
    parent_id: undefined,
    product_count: 28,
    is_featured: true,
    sort_order: 3,
    created_at: "2023-01-01T00:00:00Z",
    updated_at: "2024-01-01T00:00:00Z"
  },
  {
    id: 4,
    name: "Κρασιά & Ποτά",
    slug: "wines-beverages",
    description: "Ελληνικά κρασιά και παραδοσιακά ποτά από επιλεγμένους παραγωγούς",
    icon: "🍷",
    image: "/categories/wine.jpg",
    parent_id: undefined,
    product_count: 52,
    is_featured: true,
    sort_order: 4,
    created_at: "2023-01-01T00:00:00Z",
    updated_at: "2024-01-01T00:00:00Z"
  },
  {
    id: 5,
    name: "Φρούτα & Λαχανικά",
    slug: "fruits-vegetables",
    description: "Φρέσκα εποχιακά φρούτα και λαχανικά από ελληνικούς αγρούς",
    icon: "🍎",
    image: "/categories/fruits.jpg",
    parent_id: undefined,
    product_count: 67,
    is_featured: true,
    sort_order: 5,
    created_at: "2023-01-01T00:00:00Z",
    updated_at: "2024-01-01T00:00:00Z"
  },
  {
    id: 6,
    name: "Αρτοποιία & Ζυμαρικά",
    slug: "bakery-pasta",
    description: "Παραδοσιακό ψωμί, ζυμαρικά και αρτοσκευάσματα",
    icon: "🍞",
    image: "/categories/bread.jpg",
    parent_id: undefined,
    product_count: 34,
    is_featured: false,
    sort_order: 6,
    created_at: "2023-01-01T00:00:00Z",
    updated_at: "2024-01-01T00:00:00Z"
  },
  {
    id: 7,
    name: "Κρέατα & Αλλαντικά",
    slug: "meat-charcuterie",
    description: "Φρέσκα κρέατα και παραδοσιακά αλλαντικά από ελληνικές φάρμες",
    icon: "🥩",
    image: "/categories/meat.jpg",
    parent_id: undefined,
    product_count: 29,
    is_featured: false,
    sort_order: 7,
    created_at: "2023-01-01T00:00:00Z",
    updated_at: "2024-01-01T00:00:00Z"
  },
  {
    id: 8,
    name: "Θαλασσινά & Ψάρια",
    slug: "seafood-fish",
    description: "Φρέσκα ψάρια και θαλασσινά από ελληνικές θάλασσες",
    icon: "🐟",
    image: "/categories/seafood.jpg",
    parent_id: undefined,
    product_count: 23,
    is_featured: false,
    sort_order: 8,
    created_at: "2023-01-01T00:00:00Z",
    updated_at: "2024-01-01T00:00:00Z"
  },
  {
    id: 9,
    name: "Βότανα & Μπαχαρικά",
    slug: "herbs-spices",
    description: "Αρωματικά βότανα και μπαχαρικά από ελληνικά βουνά",
    icon: "🌿",
    image: "/categories/herbs.jpg",
    parent_id: undefined,
    product_count: 41,
    is_featured: false,
    sort_order: 9,
    created_at: "2023-01-01T00:00:00Z",
    updated_at: "2024-01-01T00:00:00Z"
  },
  {
    id: 10,
    name: "Γλυκά & Επιδόρπια",
    slug: "sweets-desserts",
    description: "Παραδοσιακά ελληνικά γλυκά και επιδόρπια",
    icon: "🍰",
    image: "/categories/sweets.jpg",
    parent_id: undefined,
    product_count: 36,
    is_featured: false,
    sort_order: 10,
    created_at: "2023-01-01T00:00:00Z",
    updated_at: "2024-01-01T00:00:00Z"
  },
  // Subcategories
  {
    id: 11,
    name: "Εξαιρετικό Παρθένο",
    slug: "extra-virgin-olive-oil",
    description: "Εξαιρετικό παρθένο ελαιόλαδο πρώτης ποιότητας",
    icon: "🫒",
    parent_id: 1,
    product_count: 28,
    is_featured: false,
    sort_order: 1,
    created_at: "2023-01-01T00:00:00Z",
    updated_at: "2024-01-01T00:00:00Z"
  },
  {
    id: 12,
    name: "Βιολογικό Ελαιόλαδο",
    slug: "organic-olive-oil",
    description: "Πιστοποιημένο βιολογικό ελαιόλαδο",
    icon: "🌱",
    parent_id: 1,
    product_count: 17,
    is_featured: false,
    sort_order: 2,
    created_at: "2023-01-01T00:00:00Z",
    updated_at: "2024-01-01T00:00:00Z"
  },
  {
    id: 13,
    name: "Φέτα",
    slug: "feta-cheese",
    description: "Αυθεντική ελληνική φέτα ΠΟΠ",
    icon: "🧀",
    parent_id: 2,
    product_count: 15,
    is_featured: false,
    sort_order: 1,
    created_at: "2023-01-01T00:00:00Z",
    updated_at: "2024-01-01T00:00:00Z"
  },
  {
    id: 14,
    name: "Κασέρι",
    slug: "kasseri-cheese",
    description: "Παραδοσιακό ελληνικό κασέρι",
    icon: "🧀",
    parent_id: 2,
    product_count: 12,
    is_featured: false,
    sort_order: 2,
    created_at: "2023-01-01T00:00:00Z",
    updated_at: "2024-01-01T00:00:00Z"
  },
  {
    id: 15,
    name: "Θυμαρίσιο Μέλι",
    slug: "thyme-honey",
    description: "Αρωματικό μέλι από άγριο θυμάρι",
    icon: "🍯",
    parent_id: 3,
    product_count: 18,
    is_featured: false,
    sort_order: 1,
    created_at: "2023-01-01T00:00:00Z",
    updated_at: "2024-01-01T00:00:00Z"
  }
];

export { mockCategories as mockData };
