apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true
    jsonData:
      httpMethod: POST
      manageAlerts: true
      alertmanagerUid: alertmanager
      timeInterval: "30s"
      queryTimeout: "60s"
      defaultRegion: "europe-west1"
      customQueryParameters: ""
      
  - name: AlertManager
    type: alertmanager
    access: proxy
    url: http://alertmanager:9093
    isDefault: false
    editable: true
    uid: alertmanager
    jsonData:
      implementation: prometheus